server {
	listen 80;
	listen [::]:80;
	server_name sub.example.com; # ToDo: replace domain

	location / {
		return 301 https://$server_name$request_uri;
	}
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name sub.example.com; # ToDo: Replace domain

	# ToDo: Replace domain (2x)
	ssl_certificate /etc/nginx/certs/sub.example.com/fullchain.pem;
	ssl_certificate_key /etc/nginx/certs/sub.example.com/key.pem;

	location / {
		proxy_pass http://127.0.0.1:8080; # ToDo: Replace port
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}
